### ISSUE TITLE
Server URL validation

### ISSUE THREAD

**Issue by parzi7al** [probot/smee-client#134]
Hi!

I have a docker stack with my own smee.io server, and I'm trying to connect my probot service to the server via service names, like that:

```yaml
smee:
  image: mysmee:local
  networks:
    - devops

probot:
  image: myimage:local
  env_file: probot.env
  networks:
    - devops
```

where _probot.env_ looks like:

```
APP_ID=xxx
WEBHOOK_PROXY_URL=http://smee:3000/MSrl0EheT9UPt8E
...
```

Could you please add `{ require_tld: false }` to `validator.isURL()` options:

https://github.com/probot/smee-client/blob/cbf0873b7ab80cdbc1e1d24f1b2aa309dc055e72/index.js#L13-L15
